---
- name: Install nginx webserver
  become: true
  apt:
    name: 
      - nginx
    update_cache: yes

- name: Copy index html file
  ansible.builtin.copy:
    src: file/index.html
    dest: /var/www/html/index.html
    follow: yes
    owner: root
    group: root
    mode: '644'
  

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
    purge: true
