---
- name: stop nginx
  ansible.builtin.service:
    name: nginx
    state: stopped


- name: remove nginx webserver
  become: true
  ansible.builtin.apt:
    name: nginx
    state: absent

- name: delete index file
  become: true
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent


- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
  


